apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

images:
  - name: 630596767614.dkr.ecr.us-east-1.amazonaws.com/gitops-argocd-dev-gitops-app
    newName: 630596767614.dkr.ecr.us-east-1.amazonaws.com/gitops-argocd-dev-gitops-app
    newTag: latest   # Prod promotion is a manual PR that updates this tag

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: gitops-app
        namespace: gitops-app
      spec:
        replicas: 3   # Extra replica in prod
