apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
  namespace: gitops-app
  labels:
    app: gitops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: gitops-app
      containers:
        - name: gitops-app
          image: 630596767614.dkr.ecr.us-east-1.amazonaws.com/gitops-argocd-dev-gitops-app
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: ENVIRONMENT
              value: "dev"
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gitops-app-secrets
                  key: GROQ_API_KEY
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 3
      restartPolicy: Always